# Generated by Django 3.1.5 on 2024-03-12 19:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic_information', '0001_initial'),
        ('globals', '0006_auto_20240218_1336'),
        ('hostel_management', '0007_hostelleave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=255)),
                ('occupied_till', models.DateField(blank=True, null=True)),
                ('vacant', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostelFine',
            fields=[
                ('fine_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=50)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HostelInventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory_name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('programme', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.CharField(blank=True, max_length=100, null=True)),
                ('room_num', models.CharField(blank=True, max_length=20, null=True)),
                ('hall_no', models.CharField(blank=True, max_length=20, null=True)),
                ('hall_id', models.CharField(blank=True, max_length=20, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hostelallotment',
            name='assigned_caretaker',
        ),
        migrations.RemoveField(
            model_name='hostelallotment',
            name='assigned_warden',
        ),
        migrations.RemoveField(
            model_name='hostelallotment',
            name='hostel_name',
        ),
        migrations.AddField(
            model_name='hall',
            name='assigned_batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hostelallotment',
            name='assignedBatch',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostelallotment',
            name='assignedCaretaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globals.staff'),
        ),
        migrations.AddField(
            model_name='hostelallotment',
            name='assignedWarden',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='globals.faculty'),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='guest_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='guest_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='guest_phone',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='guestroombooking',
            name='guest_room_id',
        ),
        migrations.AddField(
            model_name='guestroombooking',
            name='guest_room_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='nationality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='guestroombooking',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled'), ('CancelRequested', 'Cancel Requested'), ('CheckedIn', 'Checked In'), ('Complete', 'Complete'), ('Forward', 'Forward')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='staffschedule',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globals.staff'),
        ),
        migrations.DeleteModel(
            name='GuestRoomDetail',
        ),
        migrations.AddField(
            model_name='hostelinventory',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hall'),
        ),
        migrations.AddField(
            model_name='hostelfine',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hall'),
        ),
        migrations.AddField(
            model_name='hostelfine',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_information.student'),
        ),
        migrations.AddField(
            model_name='guestroom',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel_management.hall'),
        ),
    ]
